--Q1. What is the total revenue  generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used  a discount but still spent more than the average purchase amount ?
SELECT 
    customer_id,
    item_purchased,
    category,
    purchase_amount,
    discount_applied
FROM 
    customer
WHERE 
    discount_applied = 'Yes'
    AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
    );

--Q3. Which are the top 5 products with the highest average review rating?
	SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    avg_rating DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between Standard and express shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase
FROM 
    customer
WHERE 
    shipping_type IN ('Standard', 'Express')
GROUP BY 
    shipping_type;

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers .
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) AS average_spend,
Round(SUM(purchase_amount),2) AS total_revenue
from customer
WHERE subscription_status IN ('Yes','No')
group by subscription_status
order by total_revenue,average_spend desc;

--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,

    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)),
        2
    ) AS discount_percentage
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning and loyal based on their total number of previous 
-- purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(customer_id) AS total_customers
FROM 
    customer
GROUP BY 
    customer_segment
ORDER BY 
    total_customers DESC;

--Q8.What are the 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    total_purchases,
    item_rank
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
    FROM 
        customer
    GROUP BY 
        category, item_purchased
) AS ranked_products
WHERE 
    item_rank <= 3
ORDER BY 
    category, item_rank;

--Q9.Are customers who are repeat buyers ( more than 5 previous purchases ) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    subscription_status,
    COUNT(customer_id) AS total_customers
FROM 
    customer
GROUP BY 
    customer_type, subscription_status
ORDER BY 
    customer_type, total_customers DESC;

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



	
